apiVersion: v1
kind: Secret
metadata:
  name: rootca
data:
  tls.crt: {{ .Values.rootca_crt }}
  tls.key: {{ .Values.rootca_key }}
---  
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: internal-issuer
spec:
  ca:
    secretName: rootca
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: vault
spec:
  # Secret names are always required.
  secretName: vault-tls
  commonName: vault
  usages:
    - server auth
    - client auth  
  dnsNames:
{{- $replicas:=.Values.vault.server.ha.replicas }}
{{- range .Values.clusterNames }}
{{- $clusterName:= . }}
{{- range (until ($replicas | int) ) }}
  - vault-{{ . }}.{{ $clusterName }}.vault-internal.vault.svc.clusterset.local
{{- end }}
{{- end }}   
  - vault
  - vault.vault.svc
  - vault.vault.svc.cluster.local
  issuerRef:
    name: internal-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io      
